version: "3.8"

services:

  dims:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "10580:8443"
    volumes:
      - ./app:/home/dimsuser/app
