# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.8'
services:
  dims:
    container_name: "dims"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "10580:8443"
    volumes:
      - ./app:/home/dimsuser/app
      - ./logs:/home/dimsuser/logs
      - ./test:/home/dimsuser/test

  mongodb:
    container_name: "mongodb"
    image: "mongo:4.0.28"
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb/data:/data/db
