openapi: 3.0.3
info:
  title: DRS Import Managament Service API
  version: 0.1.0

paths:
  /ingest:
    post:
      operationId: initiateIngest
      summary: Initiates a new ingest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IngestRequest"
      responses:
        202:
          $ref: "#/components/responses/IngestConfirmation"
        500:
          $ref: "#/components/responses/InternalError"
        400:
          $ref: "#/components/responses/BadRequest"

components:
  responses:
    IngestConfirmation:
      description: Ingest accepted and started processing
      content:
        application/json:
          schema:
            type: object
            required:
              - package_id
              - status
              - status_code
              - message
            properties:
              package_id:
                type: string
                description: Package id associated with the ingest operation
              status:
                $ref: "#/components/schemas/ResponseStatus"
              status_code:
                type: string
                nullable: true
                description: Internally defined status code
              message:
                type: string
                description: A message describing the response
    BadRequest:
      description: Malformed request due to incorrect or missing parameters
      content:
        application/json:
          schema:
            type: object
            required:
              - status
              - status_code
              - message
            properties:
              status:
                $ref: "#/components/schemas/ResponseStatus"
              status_code:
                type: string
                nullable: true
                description: Internally defined status code
              message:
                type: string
                description: A message describing the response
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            type: object
            required:
              - status
              - status_code
              - message
            properties:
              status:
                $ref: "#/components/schemas/ResponseStatus"
              status_code:
                type: string
                description: Internally defined status code
              message:
                type: string
                description: A message describing the response
  schemas:
    IngestRequest:
      type: object
      required:
        - package_id
        - s3_path
        - s3_bucket_name
        - admin_metadata
      properties:
        package_id:
          type: string
          description: Package id to ingest
        s3_path:
          type: string
          description: S3 bucket path of the ingest object
        s3_bucket_name:
          type: string
          description: Name of the S3 bucket containing the ingest object
        admin_metadata:
          type: object
          description: Ingest admin metadata
    ResponseStatus:
      type: string
      enum: [success, pending, failure]
